//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oasis.DataLayer.oasisEntitiesModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OasisEntities : DbContext
    {
        public OasisEntities()
            : base("name=OasisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ocBatch> ocBatches { get; set; }
        public virtual DbSet<ocBranch> ocBranches { get; set; }
        public virtual DbSet<ocObservationFirstLastMeasurement> ocObservationFirstLastMeasurements { get; set; }
        public virtual DbSet<ocUser> ocUsers { get; set; }
        public virtual DbSet<ocUserAttendance> ocUserAttendances { get; set; }
        public virtual DbSet<ocUserBatchDetail> ocUserBatchDetails { get; set; }
        public virtual DbSet<Detail> Details { get; set; }
    }
}
