//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oasis.DataLayer.oasisEntitiesModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ocBranch
    {
        public int BranchId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
    }
}
