//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oasis.DataLayer.oasisEntitiesModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ocObservationFirstLastMeasurement
    {
        public int UserId { get; set; }
        public System.DateTime MonthDate { get; set; }
        public Nullable<decimal> FArmsLeft { get; set; }
        public Nullable<decimal> FArmsRight { get; set; }
        public Nullable<decimal> FChest { get; set; }
        public Nullable<decimal> FAbdomen { get; set; }
        public Nullable<decimal> FWaist { get; set; }
        public Nullable<decimal> FThighLeft { get; set; }
        public Nullable<decimal> FThighRight { get; set; }
        public Nullable<decimal> LArmsLeft { get; set; }
        public Nullable<decimal> LArmsRight { get; set; }
        public Nullable<decimal> LChest { get; set; }
        public Nullable<decimal> LAbdomen { get; set; }
        public Nullable<decimal> LWaist { get; set; }
        public Nullable<decimal> LThighLeft { get; set; }
        public Nullable<decimal> LThighRight { get; set; }
    }
}
