//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oasis.DataLayer.oasisEntitiesModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ocUser
    {
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string Mobile { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<byte> Age { get; set; }
        public string Phone { get; set; }
        public bool IsMale { get; set; }
        public bool IsTrial { get; set; }
        public short ExtensionInDays { get; set; }
        public int BranchId { get; set; }
        public bool IsAdmin { get; set; }
    }
}
